const authConstants = {
  SET_PASSWORD: "SET_PASSWORD",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SIGNUP_MESSAGE: "SIGNUP_MESSAGE",
  RESET_PASSWORD_MESSAGE: "RESET_PASSWORD_MESSAGE",
  DISABLED_MESSAGE: "DISABLED_MESSAGE",
  LOGOUT: "LOGOUT",
};

export default authConstants;
