const authConstants = {
  SUCCESS_ACTION: "SUCCESS_ACTION",
  ERROR_ACTION: "ERROR_ACTION",
  CLEAR_ACTION: "CLEAR_ACTION",
  GET_MEMBER: "GET_MEMBER",
  GET_MEMBERS: "GET_MEMBERS",
  REMOVE_MEMBER: "REMOVE_MEMBER",
  FAILED_RESPONSE: "FAILED_RESPONSE",
  UPDATE_MEMBER: "UPDATE_MEMBER",
  CREATE_MEMBER: "CREATE_MEMBER",
  GET_ADMINS: "GET_ADMINS",
};

export default authConstants;
