const newsConstants = {
  GET_NEWS: "GET_NEWS",
  GET_NEWS_BY_ID: "GET_NEWS_BY_ID",
  UPDATE_NEWS: "UPDATE_NEWS",
  CREATE_NEWS: "CREATE_NEWS",
  REMOVE_NEWS: "REMOVE_NEWS",
  FAILED_RESPONSE: "FAILED_RESPONSE",
  CLEAR_ACTIONS: "CLEAR_ACTIONS",
  GET_LATEST_NEWS: "GET_LATEST_NEWS",
};

export default newsConstants;
