const organisationConstants = {
  GET_ORGANISATIONS: "GET_ORGANISATIONS",
  CREATE_ORGANISATION: "CREATE_ORGANISATION",
  UPDATE_ORGANISATION: "UPDATE_ORGANISATION",
  GET_ORGANISATION: "GET_ORGANISATION",
  SUCCESS_ACTION: "SUCCESS_ACTION",
  ERROR_ACTION: "ERROR_ACTION",
  CLEAR_ACTION: "CLEAR_ACTION",
  FAILED_RESPONSE: "FAILED_RESPONSE",
  GET_ADMINS: "GET_ADMINS",
  REMOVE_ORGANISATION: "REMOVE_ORGANISATION",
};

export default organisationConstants;
